version: '3'
services:
  web:
    container_name: docker-node-mongo
    restart: always
    build: .
    command: mongod
    command: npm run dev
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - '27017:27017'